// dummyGroceryData.js

export const groceryItems = [
    {
        id: 1,
        name: "Organic Apples",
        price: 3.99,
        originalPrice: 4.49,
        stock: 45,
        category: "Fruits",
        unit: "per lb",
        image: "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400&h=300&fit=crop",
        rating: 4.5,
        description: "Fresh organic red apples, crisp and sweet",
        popular: true,
        discount: 11
    },
    {
        id: 2,
        name: "Bananas",
        price: 0.69,
        originalPrice: 0.79,
        stock: 120,
        category: "Fruits",
        unit: "per lb",
        image: "https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400&h=300&fit=crop",
        rating: 4.2,
        description: "Ripe yellow bananas",
        popular: true,
        discount: 13
    },
    {
        id: 3,
        name: "Carrots",
        price: 1.99,
        originalPrice: 2.29,
        stock: 78,
        category: "Vegetables",
        unit: "per lb",
        image: "https://www.lovefoodhatewaste.com/sites/default/files/styles/16_9_two_column/public/2022-06/Carrots.jpg.webp?itok=Z9YUwhCd&w=400&h=300&fit=crop",
        rating: 4.3,
        description: "Fresh organic carrots",
        popular: false,
        discount: 13
    },
    {
        id: 4,
        name: "Whole Wheat Bread",
        price: 3.49,
        originalPrice: null,
        stock: 32,
        category: "Bakery",
        unit: "loaf",
        image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=300&fit=crop",
        rating: 4.6,
        description: "Freshly baked whole wheat bread",
        popular: true,
        discount: 0
    },
    {
        id: 5,
        name: "Milk",
        price: 2.99,
        originalPrice: 3.29,
        stock: 56,
        category: "Dairy",
        unit: "gallon",
        image: "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400&h=300&fit=crop",
        rating: 4.4,
        description: "Whole milk, pasteurized",
        popular: true,
        discount: 9
    },
    {
        id: 6,
        name: "Eggs",
        price: 4.29,
        originalPrice: 4.79,
        stock: 89,
        category: "Dairy",
        unit: "dozen",
        image: "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400&h=300&fit=crop",
        rating: 4.7,
        description: "Large brown eggs",
        popular: true,
        discount: 10
    },
    {
        id: 7,
        name: "Chicken Breast",
        price: 8.99,
        originalPrice: 9.99,
        stock: 24,
        category: "Meat",
        unit: "per lb",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsatbFzK_dfKtqQ3G9HvUR_DBdCfHmkOagug&s?w=400&h=300&fit=crop",
        rating: 4.5,
        description: "Boneless skinless chicken breast",
        popular: false,
        discount: 10
    },
    {
        id: 8,
        name: "Basmati Rice",
        price: 6.99,
        originalPrice: null,
        stock: 67,
        category: "Grains",
        unit: "5 lb bag",
        image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=300&fit=crop",
        rating: 4.3,
        description: "Premium basmati rice",
        popular: false,
        discount: 0
    },
    {
        id: 9,
        name: "Orange Juice",
        price: 4.49,
        originalPrice: 4.99,
        stock: 38,
        category: "Beverages",
        unit: "64 oz",
        image: "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=400&h=300&fit=crop",
        rating: 4.4,
        description: "100% pure orange juice, not from concentrate",
        popular: true,
        discount: 10
    },
    {
        id: 10,
        name: "Potatoes",
        price: 2.49,
        originalPrice: 2.99,
        stock: 95,
        category: "Vegetables",
        unit: "5 lb bag",
        image: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400&h=300&fit=crop",
        rating: 4.1,
        description: "Russet potatoes",
        popular: false,
        discount: 17
    },
    {
        id: 11,
        name: "Greek Yogurt",
        price: 5.99,
        originalPrice: 6.49,
        stock: 42,
        category: "Dairy",
        unit: "32 oz",
        image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=300&fit=crop",
        rating: 4.8,
        description: "Plain Greek yogurt, high protein",
        popular: true,
        discount: 8
    },
    {
        id: 12,
        name: "Cheddar Cheese",
        price: 4.79,
        originalPrice: 5.29,
        stock: 53,
        category: "Dairy",
        unit: "8 oz block",
        image: "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=400&h=300&fit=crop",
        rating: 4.5,
        description: "Sharp cheddar cheese",
        popular: false,
        discount: 9
    },
    {
        id: 13,
        name: "Ground Beef",
        price: 7.49,
        originalPrice: 8.49,
        stock: 31,
        category: "Meat",
        unit: "per lb",
        image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop",
        rating: 4.4,
        description: "80/20 ground beef",
        popular: true,
        discount: 12
    },
    {
        id: 14,
        name: "Spinach",
        price: 2.99,
        originalPrice: null,
        stock: 61,
        category: "Vegetables",
        unit: "10 oz bag",
        image: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&h=300&fit=crop",
        rating: 4.2,
        description: "Fresh baby spinach leaves",
        popular: false,
        discount: 0
    },
    {
        id: 15,
        name: "Avocados",
        price: 1.49,
        originalPrice: 1.79,
        stock: 47,
        category: "Fruits",
        unit: "each",
        image: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400&h=300&fit=crop",
        rating: 4.6,
        description: "Hass avocados, ripe and ready to eat",
        popular: true,
        discount: 17
    },
    {
        id: 16,
        name: "Pasta",
        price: 1.99,
        originalPrice: null,
        stock: 84,
        category: "Grains",
        unit: "16 oz box",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTPbr4KAcSz6JldGS7AYeImCC5llcSLCOJLA&s?w=400&h=300&fit=crop",
        rating: 4.3,
        description: "Spaghetti pasta",
        popular: false,
        discount: 0
    },
    {
        id: 17,
        name: "Tomatoes",
        price: 2.29,
        originalPrice: 2.59,
        stock: 72,
        category: "Vegetables",
        unit: "per lb",
        image: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400&h=300&fit=crop",
        rating: 4.4,
        description: "Vine-ripened tomatoes",
        popular: true,
        discount: 12
    },
    {
        id: 18,
        name: "Butter",
        price: 4.29,
        originalPrice: 4.79,
        stock: 39,
        category: "Dairy",
        unit: "1 lb",
        image: "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=400&h=300&fit=crop",
        rating: 4.5,
        description: "Unsalted butter",
        popular: false,
        discount: 10
    },
    {
        id: 19,
        name: "Coffee",
        price: 8.99,
        originalPrice: 9.99,
        stock: 28,
        category: "Beverages",
        unit: "12 oz bag",
        image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&h=300&fit=crop",
        rating: 4.7,
        description: "Dark roast ground coffee",
        popular: true,
        discount: 10
    },
    {
        id: 20,
        name: "Onions",
        price: 1.79,
        originalPrice: null,
        stock: 110,
        category: "Vegetables",
        unit: "3 lb bag",
        image: "https://www.thoughtco.com/thmb/NA2t9j8ThBD7nPN913Sym1pwSYg=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/full-frame-shot-of-onions-in-market-stall-562386223-59b97e59845b340010f8d76e.jpg?w=400&h=300&fit=crop",
        rating: 4.0,
        description: "Yellow onions",
        popular: false,
        discount: 0
    },
    {
        id: 21,
        name: "Salmon Fillet",
        price: 12.99,
        originalPrice: 14.99,
        stock: 18,
        category: "Seafood",
        unit: "per lb",
        image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400&h=300&fit=crop",
        rating: 4.8,
        description: "Fresh Atlantic salmon fillet",
        popular: true,
        discount: 13
    },
    {
        id: 22,
        name: "Cereal",
        price: 3.99,
        originalPrice: 4.49,
        stock: 52,
        category: "Breakfast",
        unit: "18 oz box",
        image: "https://3449104.fs1.hubspotusercontent-na1.net/hubfs/3449104/AI-Generated%20Media/Images/Cereal%20Recall.jpeg?w=400&h=300&fit=crop",
        rating: 4.2,
        description: "Whole grain oat cereal",
        popular: false,
        discount: 11
    },
    {
        id: 23,
        name: "Bell Peppers",
        price: 2.99,
        originalPrice: 3.49,
        stock: 44,
        category: "Vegetables",
        unit: "per lb",
        image: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400&h=300&fit=crop",
        rating: 4.3,
        description: "Assorted color bell peppers",
        popular: true,
        discount: 14
    },
    {
        id: 24,
        name: "Honey",
        price: 6.49,
        originalPrice: null,
        stock: 29,
        category: "Condiments",
        unit: "24 oz jar",
        image: "https://images.unsplash.com/photo-1587049352851-8d4e89133924?w=400&h=300&fit=crop",
        rating: 4.6,
        description: "Pure raw honey",
        popular: false,
        discount: 0
    },
    {
        id: 25,
        name: "Ice Cream",
        price: 4.99,
        originalPrice: 5.99,
        stock: 36,
        category: "Frozen",
        unit: "pint",
        image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&h=300&fit=crop",
        rating: 4.9,
        description: "Vanilla bean ice cream",
        popular: true,
        discount: 17
    },
    {
        id: 26,
        name: "Broccoli",
        price: 1.99,
        originalPrice: null,
        stock: 58,
        category: "Vegetables",
        unit: "per lb",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5HI921PGF_R6Kqm0ESAHt9BT9snCb1lghkQ&s?w=400&h=300&fit=crop",
        rating: 4.1,
        description: "Fresh broccoli florets",
        popular: false,
        discount: 0
    },
    {
        id: 27,
        name: "Olive Oil",
        price: 9.99,
        originalPrice: 11.99,
        stock: 41,
        category: "Condiments",
        unit: "17 oz bottle",
        image: "https://images.unsplash.com/photo-1533050487297-09b450131914?w=400&h=300&fit=crop",
        rating: 4.7,
        description: "Extra virgin olive oil",
        popular: true,
        discount: 17
    },
    {
        id: 28,
        name: "Oranges",
        price: 3.49,
        originalPrice: 3.99,
        stock: 63,
        category: "Fruits",
        unit: "per lb",
        image: "https://images.unsplash.com/photo-1547514701-42782101795e?w=400&h=300&fit=crop",
        rating: 4.5,
        description: "Navel oranges, sweet and juicy",
        popular: false,
        discount: 13
    },
    {
        id: 29,
        name: "Bacon",
        price: 5.99,
        originalPrice: 6.99,
        stock: 27,
        category: "Meat",
        unit: "12 oz package",
        image: "https://images.unsplash.com/photo-1528607929212-2636ec44253e?w=400&h=300&fit=crop",
        rating: 4.6,
        description: "Thick cut bacon",
        popular: true,
        discount: 14
    },
    {
        id: 30,
        name: "Garlic",
        price: 1.29,
        originalPrice: null,
        stock: 92,
        category: "Vegetables",
        unit: "per bulb",
        image: "https://cdn.britannica.com/37/174537-050-950EE618/Bulbs-cloves-garlic.jpg?w=400&h=300&fit=crop",
        rating: 4.0,
        description: "Fresh garlic bulbs",
        popular: false,
        discount: 0
    }
];

// Optional: Additional utility data
export const categories = [
    "Fruits", "Vegetables", "Dairy", "Meat", "Bakery",
    "Beverages", "Grains", "Seafood", "Frozen", "Breakfast", "Condiments"
];

// Helper function to get items by category
export const getItemsByCategory = (category) => {
    return groceryItems.filter(item => item.category === category);
};

// Helper function to get popular items
export const getPopularItems = () => {
    return groceryItems.filter(item => item.popular);
};

// Helper function to get items on sale
export const getItemsOnSale = () => {
    return groceryItems.filter(item => item.discount > 0);
};